app/models/Order.php
<?php

namespace app\models;

use Yii;
use app\models\Item;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "cms_order".
 *
 * @property integer $id
 * @property string $create_time
 * @property string $update_time
 * @property integer $status
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $address
 * @property integer $mode_delivery
 * @property integer $mode_payment
 * @property string $user_comment
 * @property string $admin_comment
 *
 * @property Item[] $items
 */
class Order extends \yii\db\ActiveRecord
{
    private $_crateItemsFromCart = false;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms_order';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'phone', 'email'], 'required'],
            [['email'], 'email'],
            // [['phone'], 'safe'],
            [['status', 'mode_delivery', 'mode_payment'], 'integer'],
            [['address', 'user_comment', 'admin_comment'], 'string'],
            [['name', 'phone', 'email'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'create_time' => 'Время создания',
            'update_time' => 'Время обновления',
            'status' => 'Статус',
            'name' => 'Имя',
            'phone' => 'Телефон',
            'email' => 'Email',
            'address' => 'Адрес',
            'mode_delivery' => 'Способ доставки',
            'mode_payment' => 'Способ оплаты',
            'user_comment' => 'Комментарий',
            'admin_comment' => 'Комментарий Админа',
            'totalCost' => 'Сумма заказа',
            'totalCount' => 'Кол-во продуктов',
            'count' => 'Кол-во позиций',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(Item::className(), ['order_id' => 'id']);
    }


    public function beforeSave()
    {
        if ($this->isNewRecord) {
            $this->create_time = date('Y-m-d H:i:s');
            $this->_crateItemsFromCart = true;
        }
        $this->update_time = date('Y-m-d H:i:s');

        return true;
    }

    public function afterSave()
    {
        if ($this->_crateItemsFromCart) {
            foreach ( \Yii::$app->cart->getPositions() as $position ) {
                $item = new Item();
                $item->order_id = $this->id;
                $item->product_id = $position->id;
                $item->count = $position->getQuantity();
                $item->save();
            }
            \Yii::$app->cart->removeAll();
        }

        return true;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemsProvider()
    {

        return new ActiveDataProvider([
            'query' => Item::find()->where(['order_id'=>$this->id]),
        ]);
    }

    public function getTotalCost()
    {
        $sum = 0;
        foreach ($this->items as $item) {
            $sum += $item->cost;
        }
        return $sum;
    }

    public function getTotalCount()
    {
        $count = 0;
        foreach ($this->items as $item) {
            $count += $item->count;
        }
        return $count;
    }

    public function getCount()
    {
        return count($this->items);
    }
}

app/controllers/OrderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Order;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use app\bem\BemController;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;


/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends BemController
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['admin-view', 'index', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Order::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionSuccess($id)
    {

        return $this->renderBemjson('success', ['model' => $this->findModel($id),]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionAdminView($id)
    {
        return $this->render('admin-view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['success', 'id' => $model->id]);
        } else {
            return $this->renderBemjson('create', ['model' => $model]);
        }
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['admin-view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

app/controllers/ProductController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Product;
use app\bem\BemController;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yz\shoppingcart\ShoppingCart;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use app\models\ProductImg;
use app\models\Img;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends BemController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['admin-index', 'update', 'delete', 'create', 'admin-view'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $products = Product::find()->all();

        return $this->renderBemjson('index', ['products'=>$products]);
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionAdminIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Product::find(),
        ]);

        return $this->render('admin-index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {

        return $this->renderBemjson('view.handlebars', ['product' => $this->findModel($id)]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionAdminView($id)
    {
        return $this->render('admin-view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['admin-view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {



            return $this->redirect(['admin-view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['admin-index']);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Добавляет позицию в корзину
     * @param  integer $id - id продукта
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionAddToCart($id, $count=1)
    {
        $cart = Yii::$app->cart;

        $model = $this->findModel($id);

        $cart->put($model, $count);

        // если аякс - говорю, что получилось
        if (Yii::$app->request->isAjax) {
            echo '{result:"ok"}';
            Yii::$app->end();
        } else {
            return $this->redirect(['cart-view']);
        }
    }

    /**
     * Делает изображение главным
     * @param  integer $product_id - id продукта
     * @param  integer $img_id - id файла
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionMainImg($product_id, $img_id)
    {
        $model = $this->findModel($product_id);

        // проверяю, что id присланного изображение в числе тех, которые закреплены
        foreach ($model->images as $image) {
            if ($image->id == $img_id) {
                $model->main_img_id = $img_id;
                $model->save(false);
                return $this->redirect(Yii::$app->request->referrer);
            }
        }

        return 'Не удалось сделать изображение главным';
    }
}

app/views/order/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'create_time')->textInput() ?>

    <?= $form->field($model, 'update_time')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'mode_delivery')->textInput() ?>

    <?= $form->field($model, 'mode_payment')->textInput() ?>

    <?= $form->field($model, 'user_comment')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'admin_comment')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/order/admin-view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?= Html::a('К списку заказов', ['/order/index']) ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'create_time',
            'update_time',
            'status',
            'name',
            'phone',
            'email:email',
            'address:ntext',
            'mode_delivery',
            'mode_payment',
            'user_comment:ntext',
            'admin_comment:ntext',
            'totalCost',
            'count',
            'totalCount',
        ],
    ]) ?>

    <hr>
    <h3>Заказано</h3>
    <?= GridView::widget([
        'dataProvider' => $model->itemsProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'label'=>'Название',
                'format'=>'html',
                'value'=>function ($data) {
                    return Html::a($data->product->name, ['/product/view', 'id'=>$data->product->id]);
                },
            ],
            'product.price',
            'count',
            'cost',
        ],
    ]); ?>


</div>

app/views/order/create.php
<?php

// var_dump($model->errors);
?>

{
    block : 'order-create',
    content : [
        {
            block : 'title',
            content : '<h3>Оформление заказа</h3>'
        },
        {
            block : 'order-form',
            tag : 'form',
            attrs : {action : '', method : 'post'},
            content : [
                {
                    elem : 'error-summary',
                    content : [
                        {
                            elem : 'error-explain',
                            content : 'Необходимо исправить следующие ошибки'
                        },
                        {
                            elem : 'errors-list',
                            tag : 'ol',
                            content : [
                                <?php foreach ($model->errors as $error) {?>
                                    {
                                        elem : 'error-message',
                                        tag : 'li',
                                        content : '<?= implode(', ', $error) ?>',
                                    },
                                <?php } ?>
                            ]
                        }
                    ]
                },
                {
                    block : 'order-input-name',
                    content : [
                        {
                            elem : 'label-name',
                            tag : 'label',
                            attrs : {for : 'order-name'},
                            content : 'Имя'
                        },
                        {
                            elem : 'input-name',
                            tag : 'input',
                            attrs : {
                                id : 'order-name',
                                name : 'Order[name]',
                                type : 'text',
                                value : '<?= $model->name ?>',
                            },
                        }
                    ]
                },
                {
                    block : 'order-input-phone',
                    content : [
                        {
                            elem : 'label-phone',
                            tag : 'label',
                            attrs : {for : 'order-phone'},
                            content : 'Телефон'
                        },
                        {
                            elem : 'input-phone',
                            tag : 'input',
                            attrs : {
                                id : 'order-phone',
                                name : 'Order[phone]',
                                type : 'text',
                                value : '<?= $model->phone ?>',
                            }
                        }
                    ]
                },
                {
                    block : 'order-input-email',
                    content : [
                        {
                            elem : 'label-email',
                            tag : 'label',
                            attrs : {for : 'order-email'},
                            content : 'Email'
                        },
                        {
                            elem : 'input-name',
                            tag : 'input',
                            attrs : {
                                id : 'order-email',
                                name : 'Order[email]',
                                type : 'text',
                                value : '<?= $model->email ?>',
                            },
                        }
                    ]
                },
                {
                    block : 'order-form-submit',
                    content : [
                        {
                            elem : 'button-submit',
                            cls : 'btn btn-success',
                            tag : 'button',
                            attrs : {type : 'submit', name : '_csrf', value : '<?=Yii::$app->request->getCsrfToken()?>'},
                            content : 'Отправить',
                        }
                    ]
                },
                {
                    block : 'csrf-input',
                    content : [
                        {
                            elem : 'input-csrf',
                            tag : 'input',
                            attrs : {type : 'hidden', name : '_csrf', value : '<?=Yii::$app->request->getCsrfToken()?>'},
                        }
                    ]
                }

            ]
        }
    ]
}

app/views/order/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Orders';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">

    <div class="order-index">

        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a('Create Order', ['create'], ['class' => 'btn btn-success']) ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',
                'create_time',
                // 'update_time',
                'status',
                'name',
                'phone',
                'email:email',
                'totalCost',
                // 'mode_delivery',
                // 'mode_payment',
                // 'user_comment:ntext',
                // 'admin_comment:ntext',

                [
                    'class' => 'yii\grid\ActionColumn',
                    'buttons' => [
                        'view' => function ($url, $model, $key) {
                            return Html::a(
                                '<span class="glyphicon glyphicon-eye-open"></span>',
                                ['/order/admin-view', 'id'=>$model->id],
                                [
                                    'title' => Yii::t('yii', 'View'),
                                    'data-pjax' => '0',
                                ]
                            );
                        },
                    ]
                ],
            ],
        ]); ?>

    </div>
</div>

app/views/order/success.php
{
    block : 'order-success',
    content : [
        {
            block : 'title',
            tag : 'h2',
            content : 'Ваш заказ успешно создан!'
        },
        {
            block : 'description',
            tag : 'p',
            content : 'Вскоре мы с вами свяжемся! Номер вашего заказа #<?= $model->id ?>'
        },

    ]
}

app/views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Update Order: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="container">
    <div class="order-update">

        <h1><?= Html::encode($this->title) ?></h1>

        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>

    </div>
</div>