app/models/Product.php
<?php

namespace app\models;

use Yii;
use yz\shoppingcart\CartPositionInterface;
use yz\shoppingcart\CartPositionTrait;
use app\models\Group;
use app\models\ProductImg;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;

/**
 * This is the model class for table "cms_product".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $price
 *
 * @property Item[] $items
 */
class Product extends \yii\db\ActiveRecord implements CartPositionInterface
{
    use CartPositionTrait;

    public function getPrice()
    {
        return $this->price;
    }

    public function getId()
    {
        return $this->id;
    }


    public function behaviors()
    {
        return [
            'uploadFile' => [
                'class' => \app\components\FilesBehavior::className(),
                'filesAttributes' => ['images'],
                'multiple' => true,
                'fileModelClass' => 'app\models\ProductImg'
            ],

        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms_product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description', 'price'], 'required'],
            [['description'], 'string'],
            [['price', 'group_id'], 'number'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'group_id' => 'Родительская группа',
            'name' => 'Название',
            'description' => 'Описание',
            'price' => 'Цена',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(Item::className(), ['product_id' => 'id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUrl()
    {
        return Url::to(['/product/view', 'id'=>$this->id]);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(Group::className(), ['id' => 'group_id']);
    }

    public function beforeSave()
    {
        // если эта группа прикрепляется к другой - выставляю у родительской тип "папка"
        if ($this->group) {
            $parent = $this->group;
            $parent->type = Group::TYPE_PRODUCT;
            if ($parent->save()) {
                return true;
            } else {
                $this->addError(
                    'parent_id',
                    'У родительской группы не удалось установить тип '.
                        Group::typeText(Group::TYPE_PRODUCT) . ' ('.$parent->errors['type'][0].')');

                return false;
            }
        }

        return true;
    }


    public function getImgsDataProvider()
    {
        return $provider = new ActiveDataProvider([
            'query' => ProductImg::find()->where(['related_id' => $this->id])
                ->andWhere(['related_class' => self::className()])
                ->andWhere(['related_attribute' => 'images']) ,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
    }


    public function getMainThumb()
    {
        if ($this->main_img_id) {
            return ProductImg::findOne($this->main_img_id);
        } else {
            return null;
        }
    }
}

app/controllers/FileController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\File;
use yii\web\Controller;

class FileController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(Yii::$app->request->referrer);
    }


    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return File the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = File::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

app/controllers/GroupController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Group;
use app\models\Thumb;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\bem\BemController;
use yii\web\UploadedFile;
use himiklab\thumbnail\EasyThumbnailImage;

/**
 * GroupController implements the CRUD actions for Group model.
 */
class GroupController extends BemController
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['admin-view', 'admin-index', 'update', 'delete', 'create'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Lists all Group models.
     * @return mixed
     */
    public function actionIndex()
    {
        $groups = Group::find()->where('parent_id IS NULL')->all();

        return $this->renderBemjson('index.handlebars', ['groups'=>$groups]);
    }

    /**
     * Lists all Group models.
     * @return mixed
     */
    public function actionAdminIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Group::find(),
        ]);

        return $this->render('admin-index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Group model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $group = $this->findModel($id);

        // var_dump(is_array($group->products[0]));
        if ($group->type == Group::TYPE_PRODUCT) {
            return $this->renderBemjson('view_product.handlebars', [
                'group' => $group,
            ]);
        } else if ($group->type == Group::TYPE_GROUP) {
            return $this->renderBemjson('view_group.handlebars', [
                'group' => $group,
            ]);
        }

    }

        /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionAdminView($id)
    {

        return $this->render('admin-view', [
            'model' => $this->findModel($id),
        ]);
    }


    /**
     * Creates a new Group model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Group();
        // $model->thumb_id = $this->saveThumb($model, 'create');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['admin-view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }



    /**
     * Updates an existing Group model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post()) && $model->save() ) {
            return $this->redirect(['admin-view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Group model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['admin-index']);
    }

    /**
     * Finds the Group model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Group the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Group::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }



}

app/controllers/ProductController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Product;
use app\bem\BemController;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yz\shoppingcart\ShoppingCart;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use app\models\ProductImg;
use app\models\Img;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends BemController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['admin-index', 'update', 'delete', 'create', 'admin-view'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $products = Product::find()->all();

        return $this->renderBemjson('index', ['products'=>$products]);
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionAdminIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Product::find(),
        ]);

        return $this->render('admin-index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {

        return $this->renderBemjson('view.handlebars', ['product' => $this->findModel($id)]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionAdminView($id)
    {
        return $this->render('admin-view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['admin-view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {



            return $this->redirect(['admin-view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['admin-index']);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Добавляет позицию в корзину
     * @param  integer $id - id продукта
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionAddToCart($id, $count=1)
    {
        $cart = Yii::$app->cart;

        $model = $this->findModel($id);

        $cart->put($model, $count);

        // если аякс - говорю, что получилось
        if (Yii::$app->request->isAjax) {
            echo '{result:"ok"}';
            Yii::$app->end();
        } else {
            return $this->redirect(['cart-view']);
        }
    }

    /**
     * Делает изображение главным
     * @param  integer $product_id - id продукта
     * @param  integer $img_id - id файла
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionMainImg($product_id, $img_id)
    {
        $model = $this->findModel($product_id);

        // проверяю, что id присланного изображение в числе тех, которые закреплены
        foreach ($model->images as $image) {
            if ($image->id == $img_id) {
                $model->main_img_id = $img_id;
                $model->save(false);
                return $this->redirect(Yii::$app->request->referrer);
            }
        }

        return 'Не удалось сделать изображение главным';
    }
}

app/views/product/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Group;
use app\models\Img;
use kartik\file\FileInput;
use himiklab\thumbnail\EasyThumbnailImage;


/* @var $this yii\web\View */
/* @var $model app\models\Product */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-form">

    <?php $form = ActiveForm::begin([
        'options'=>['enctype'=>'multipart/form-data']
    ]); ?>

    <?= $form->field($model, 'group_id')->dropDownList(
        ArrayHelper::map(Group::find()->all(), 'id', 'name'),
        ['prompt'=>'Выберите группу, к которой прикреить продукт']
    ) ?>


    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'images[]')->widget(FileInput::classname(), [
        'options' => [
            'accept' => 'image/*',
            'multiple' => true,
            'attribute' => 'images',
        ],
        'pluginOptions' => [
            'showCaption' => false,
            'showRemove' => false,
            'showUpload' => false,
            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
            'browseLabel' =>  'Добавить изображения'
        ],
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/product/_image.php
<?php
use yii\helpers\Html;
use himiklab\thumbnail\EasyThumbnailImage;



?>
<div class="row">
    <div class="col-md-6">
        <?php echo Html::img($model->thumbUrl)?>
    </div>
    <div class="col-md-6">
        <div>
        <?= $product->main_img_id == $model->id ?
            '<b>Главное изображение</b>' :
            Html::a(
                'Cделать главным',
                ['/product/main-img', 'product_id'=>$product->id, 'img_id'=>$model->id]
            )
        ?>
        </div>
        <div>
            <?= Html::a('Удалить', ['/file/delete', 'id'=>$model->id], ['data-confirm' => 'Действиетльно удалить изображение?',])?>
        </div>

    </div>
</div>
<hr>

app/views/product/admin-index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Продукты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">

        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a('Просмотр', ['/group/index'], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Создать продукт', ['create'], ['class' => 'btn btn-success']) ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',
                'group.name',
                'name',
                'description',
                'price',


                [
                    'class' => 'yii\grid\ActionColumn',
                    'buttons' => [
                        'view' => function ($url, $model, $key) {
                            return Html::a(
                                '<span class="glyphicon glyphicon-eye-open"></span>',
                                ['/product/view', 'id'=>$model->id],
                                [
                                    'title' => Yii::t('yii', 'View'),
                                    'data-pjax' => '0',
                                ]
                            );
                        },
                    ]
                ],
            ],
        ]); ?>

</div>

app/views/product/admin-view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model app\models\Product */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('К списку продуктов', ['admin-index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-link pull-right',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'group.name',
            'name',
            'description:ntext',
            'price',
        ],
    ]) ?>

    <h3>Изображения</h3>
    <?php

    var_dump($model->mainThumb->id);

    echo ListView::widget( [
        'dataProvider' => $model->imgsDataProvider,
        'itemView' => '_image',
        'viewParams' => ['product'=>$model],
    ]) ?>


    <?php
    // var_dump($model->images);
    // foreach ($model->image as $image) {
    //     var_dump($image->delete());
    // }
     ?>
    <?= Html::a('Добавить изображения', ['update', 'id' => $model->id], ['class' => 'btn btn-success']) ?>


</div>

app/views/product/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Product */

$this->title = 'Create Product';
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/views/product/index.php
({
    block: 'main',
    content: [
        {
            block : "link-to-cart",
            tag : 'a',
            cls : "btn btn-success btn-sm",
            attrs : {href:'/site/cart'},
            content : 'Перейти в корзину',
        },
        {
            tag : 'h1',
            content : 'Список продуктов',
        },
        {
            block: "product-list",
            content: [
                <?php foreach ($products as $product) { ?>
                    {
                        block : 'product',

                        content : [
                            {
                                elem : 'title',
                                content : '<?= $product->name ?>'
                            },
                            {
                                elem : 'price',
                                content : 'цена: <?= $product->price ?>'
                            },
                            {
                                elem : 'description',
                                content : '<?= $product->description ?>'
                            },
                            {
                                block : 'add-to-cart',
                                tag : 'button',
                                cls : 'btn btn-primary btn-sm',
                                content : 'Добавить в корзину',
                                js : {
                                    product_id : <?= $product->id ?>
                                }
                            },
                            {
                                tag : 'hr',
                            },
                        ],
                    },
                <?php } ?>
            ],
        },

        {
            block : 'cart-add-modal',
            body_text : 'f',
            buttons : {
                "dismiss" : {
                    block : 'to-cart-button',
                    cls : 'btn btn-sm btn-default',
                    attrs : {'data-dismiss' : 'modal'},
                    content : 'Продолжить',
                },
                "to-cart" : true,
            }
        }

    ],
})

app/views/product/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Product */

$this->title = 'Update Product: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>