app/models/Group.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Url;
use app\components\ImgBehavior;

use himiklab\thumbnail\EasyThumbnailImage;
/**
 * This is the model class for table "cms_group".
 *
 * @property integer $id
 * @property integer $parent_id
 * @property integer $type
 * @property string $name
 * @property string $description
 *
 * @property Group $parent
 * @property Group[] $groups
 * @property Product[] $products
 */
class Group extends \yii\db\ActiveRecord
{
    const TYPE_PRODUCT = 0;
    const TYPE_GROUP = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms_group';
    }

    public function behaviors()
    {
        return [
            'uploadFile' => [
                'class' => \app\components\FilesBehavior::className(),
                'filesAttributes' => ['image'],
                'multiple' => false
            ],
            'imgBehavior' => [
                'class' => \app\components\ImgBehavior::className(),
                'width' => Yii::$app->settings->get('groups.width'),
                'height' => Yii::$app->settings->get('groups.height'),
                'defaultThumbPath' => Yii::getAlias('@webroot') .'/images/default_group.png',
            ]
        ];
    }

    public function getFilePath()
    {
        return $this->image ? $this->image->filePath : false;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'type'], 'integer'],
            [['name'], 'required'],
            [['type'], 'canBeThisType'],
            [['description'], 'string'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    public function canBeThisType($attr, $params)
    {
        $reason = false;

        // к группе уже прикреплены продукты => её нельзя сделать папкой групп
        if ($this->$attr == self::TYPE_GROUP && count($this->products)) {
            $reason = 'к группе уже прикреплены продукты';
        } else if ($this->$attr == self::TYPE_PRODUCT && count($this->groups)) {
            $reason = 'к группе уже прикреплены подгруппы';
        }

        if ($reason) {
            $this->addError(
                $attr,
                'Группа не может быть типа "'.$this->typeText.'", так как '.$reason
            );
        }
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => 'Родительская группа',
            'type' => 'Тип',
            'name' => 'Группа',
            'description' => 'Описание',
            'typeText' => 'Тип группы',
            // 'img_id' => 'Миниатюра',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(Group::className(), ['id' => 'parent_id']);
    }



    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroups()
    {
        return $this->hasMany(Group::className(), ['parent_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['group_id' => 'id']);
    }

    public function getTypeText()
    {
        return $this->typeList[$this->type] ?: '(тип не определён)';
    }

    public static function typeText($type=self::TYPE_PRODUCT)
    {
        return self::typeList()[$type];
    }

    public function getTypeList()
    {
        return self::typeList();
    }

    public static function typeList()
    {
        return [
            self::TYPE_PRODUCT => 'Каталог товаров',
            self::TYPE_GROUP => 'Папка'
        ];
    }

    public function getUrl()
    {
        return Url::to(['/group/view/', 'id'=>$this->id]);
    }



    public function beforeSave()
    {
        // если эта группа прикрепляется к другой - выставляю у родительской тип "папка"
        if ($this->parent) {
            $parent = $this->parent;
            $parent->type = self::TYPE_GROUP;
            if ($parent->save()) {
                return true;
            } else {
                // если не получилось выставить - добавляю в список ошибок причину
                $this->addError(
                    'parent_id',
                    'У родительской группы не удалось установить тип '.
                        self::typeText(self::TYPE_GROUP) . ' ('.$parent->errors['type'][0].')');

                return false;
            }
        }

        return true;
    }




}

app/controllers/GroupController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Group;
use app\models\Thumb;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\bem\BemController;
use yii\web\UploadedFile;
use himiklab\thumbnail\EasyThumbnailImage;

/**
 * GroupController implements the CRUD actions for Group model.
 */
class GroupController extends BemController
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['admin-view', 'admin-index', 'update', 'delete', 'create'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Lists all Group models.
     * @return mixed
     */
    public function actionIndex()
    {
        $groups = Group::find()->where('parent_id IS NULL')->all();

        return $this->renderBemjson('index.handlebars', ['groups'=>$groups]);
    }

    /**
     * Lists all Group models.
     * @return mixed
     */
    public function actionAdminIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Group::find(),
        ]);

        return $this->render('admin-index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Group model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $group = $this->findModel($id);

        // var_dump(is_array($group->products[0]));
        if ($group->type == Group::TYPE_PRODUCT) {
            return $this->renderBemjson('view_product.handlebars', [
                'group' => $group,
            ]);
        } else if ($group->type == Group::TYPE_GROUP) {
            return $this->renderBemjson('view_group.handlebars', [
                'group' => $group,
            ]);
        }

    }

        /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionAdminView($id)
    {

        return $this->render('admin-view', [
            'model' => $this->findModel($id),
        ]);
    }


    /**
     * Creates a new Group model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Group();
        // $model->thumb_id = $this->saveThumb($model, 'create');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['admin-view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }



    /**
     * Updates an existing Group model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post()) && $model->save() ) {
            return $this->redirect(['admin-view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Group model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['admin-index']);
    }

    /**
     * Finds the Group model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Group the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Group::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }



}

app/views/group/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Group;
// use app\models\Img;
use kartik\file\FileInput;
use himiklab\thumbnail\EasyThumbnailImage;

/* @var $this yii\web\View */
/* @var $model app\models\Group */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="group-form">

    <?php $form = ActiveForm::begin([
        'options'=>['enctype'=>'multipart/form-data']
    ]); ?>

    <?= $form->field($model, 'parent_id')->dropDownList(
        $model->isNewRecord ?
            ArrayHelper::map(Group::find()->all(), 'id', 'name') :
            ArrayHelper::map(Group::find()->where('id != :id', [':id'=>$model->id])->all(), 'id', 'name'),
        ['prompt'=>'(не задано)']
    ) ?>

    <?= $form->field($model, 'type')->dropDownList($model->typeList ) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?php $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?php
        echo Html::img($model->thumbUrl, ['alt'=>'Миниатюра']);
    ?>

    <?= $form->field($model, 'image[]')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*'],
        'pluginOptions' => [
            'showCaption' => false,
            'showRemove' => false,
            'showUpload' => false,
            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
            'browseLabel' =>  $model->isNewRecord ? 'Заменить обложку' : 'Выбрать обложку'
        ],
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>


    <?php ActiveForm::end(); ?>

</div>

app/views/group/admin-index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Groups';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Просмотр', ['index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Создать группу', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'parent.name',
            'typeText',
            [
                'attribute'=>'name',
                'format'=>'html',
                'value'=>function ($data) {
                    return Html::a($data->name, ['/group/admin-view', 'id'=>$data->id]);
                }
            ],
            'description:ntext',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

app/views/group/admin-view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Group */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Groups', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('К списку групп', ['admin-index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-link pull-right',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'typeText',
            'name',
            [
                'attribute'=>'parent_id' ,
                'format'=>'html',
                'value'=> $model->parent ?
                    Html::a($model->parent->name,
                        ['/group/admin-view', 'id'=>$model->parent->id]
                ) :
                    '(не задана)',

            ],
            'description:ntext',
            [
                'attribute'=>'image' ,
                'format'=>'html',
                'value'=> Html::img($model->thumbUrl)

            ],
        ],
    ]) ?>

<?php

// echo Html::img($model->thumbUrl);
// var_dump($model->filePath);

// echo Html::img($model->thumbUrl, ['alt'=>'abc']);
?>
</div>

app/views/group/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Group */

$this->title = 'Создание группы';
$this->params['breadcrumbs'][] = ['label' => 'Groups', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/views/group/index.php
({
    block: 'main',
    cls: 'container',
    content: [
        {
            tag : 'h1',
            content : 'Список групп',
        },
        {
            block: "product-list",
            content: [
                <?php foreach ($groups as $group) { ?>
                    {
                        block : 'product-item',

                        content : [
                            {
                                block : 'link',
                                url : '<?= $group->url ?>',
                                content : '<?= $group->name ?>'
                            },
                            {
                                tag : 'br',
                            },
                            {
                                block : 'image',
                                url : '<?= $group->thumbUrl ?>',
                                title : 'Все подробности на bem.info'
                            },
                            {
                                tag : 'hr',
                            },
                        ],
                    },
                <?php } ?>
            ],
        },



    ],
})

app/views/group/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Group */

$this->title = 'Update Group: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Groups', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>